project:
  type: website
  output-dir: docs
  render:
    - syllabus.qmd
    - computers_lab.qmd
    - project_1.md
    - project_2.md
    - project_3.md
    - project_4.md
    - lab_8.qmd
    - lab_10.qmd
    - lab_11.qmd
    - final_proj.md
    - introduction.qmd
    - computers.qmd
    - computers_slides.qmd
    - terminals.qmd
    - what_is_gis.qmd
    - some_basic_gis_concepts.qmd
    - data_storage.qmd
    - a_quick_intro_to_qgis.qmd
    - intro_geospatial_data.qmd
    - w2_house_keeping.qmd
    - projections_etc.qmd
    - spatial_data_models.qmd
    - vector_tutorial.qmd
    - dem_slides.qmd
    - finding_gis_data.qmd
    - w3_house_keeping.qmd
    - remote_sensing.qmd
    - statistics_101.qmd
    - segmentation.qmd
    - rasterizing_by_attribute.qmd
    - georeferencing.qmd
    - focal_filters.qmd
    - intro_excel_arc.qmd
    - intro_excel_arc_tmp.qmd
    - index.qmd
  resources:
    - .nojekyll

format:
  revealjs:
    theme: dracula
    slide-number: true           
    controls: true               
    progress: true               
    hash: true                   
    center: true                 
    transition: slide            
    background-transition: fade  
    code-block-height: 500px     


editor:
  render-on-save: true